### ISSUE TITLE
Cleanup and deploy

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#1]
- [x] Transfer related css/scss from datproject.org repo to here
- [x] (optional) Use tachyons instead of flexboxgrid.com 
- [ ] Make sure all links work
- [ ] Update footer
- [x] (optional) Prebuild all static pages with netlify to use static site.. otherwise, just deploy as-is on server.
- [ ] redirect datproject.org/<key> to datbase.org (should we redirect everything that isnt caught?)
- [ ] Deploy to datproject.org after https://github.com/datproject/datproject.org/pull/609 is complete.

**Comment by joehand** [comment]
Yay, nice!

> Transfer related css/scss from datproject.org repo to here

Happy to do this. I ❤️ css! May be a chance for me to consolidate what I've done with the other sites so I stop redoing the same thing.

> Prebuild all static pages with netlify to use static site.. otherwise, just deploy as-is on server.

Is there an easy way to do this? I tried before but never figured it out. Since we have the blog redirects we may want the server anyways.

**Comment by karissa** [comment]
yeah i'm down to keep the server

**Comment by joehand** [comment]
Note: make sure we have the datproject.org paper link. Its not in the server right now.

Old implementation:

```js
app.get('/paper', function (req, res) {
    fs.createReadStream(path.join(__dirname, '..', 'public', 'dat-paper.pdf')).pipe(res)
})
```

**Comment by joehand** [comment]
Done!
