### ISSUE TITLE
client-side choo logger

### ISSUE THREAD

**Issue by laurengarcia** [datproject/datproject.org#179]

**Comment by clkao** [comment]
are there specific things that should be logged in certain ways?

**Comment by laurengarcia** [comment]
oh, this one is more exploratory -- i had seen that there is a `choo` debug logger for browser console, it seemed nice when i saw a demo.

**Comment by clkao** [comment]
Maybe we can remove this from the alpha milestone then?

**Comment by laurengarcia** [comment]
sure.

**Comment by karissa** [comment]
@yoshuawuyts thoughts?

**Comment by yoshuawuyts** [comment]
@karissa we could use https://github.com/yoshuawuyts/choo-log
