### ISSUE TITLE
list of dat applications

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#19]
would be awesome to have a list of the applications developed by the community that use dat-related stuff under the hood -- beaker, mapeo, rotonde, hyperic, dat desktop, datbase, cli, etc.. (what else?)

**Comment by millette** [comment]
There's https://github.com/dat-land/awesome-dat but http://awesome.datproject.org/ is lagging a bit behind.

**Comment by joehand** [comment]
We have this started on dat.land.
