### ISSUE TITLE
loading animation or messaging when there is no server-rendered file list 

### ISSUE THREAD

**Issue by laurengarcia** [datproject/datproject.org#248]

**Comment by clkao** [comment]
There are two different waiting time here:
1. the server is trying to prerender and there's a 3sec timeout.
2. the client trying to join swarm and there's a wait before we get an open archive.

for (2) it's easy to add a loading state. but for (1) to work it seems to defeat the purpose or server rendering.

**Comment by karissa** [comment]
this is all server rendered now and much faster than before
