### ISSUE TITLE
dat.land archives do not resume after break in connectivity

### ISSUE THREAD

**Issue by laurengarcia** [datproject/datproject.org#259]
@clkao found this. chime in if you have addt'l info. he mentioned in irc that there is some signalhub activity after resuming, but not all functionality returns.

**Comment by clkao** [comment]
This happens with a local signalhub as well, and usually comes with the minus peer count:
![screen shot 2016-09-18 at 10 17 27 am](https://cloud.githubusercontent.com/assets/69736/18612305/42a0b474-7d89-11e6-9f45-7463208620fe.png)

**Comment by clkao** [comment]
(failed) attempt to reproduce:
1. In window 1 (incognito), create new archive and upload a bunch of files
2. in window 2 (regular), browser the archive url created in window 1
3. observe window 2 gets archive content list, both windows have Source: 1
4. go to dev console of window 1, click "Offline"
5. observe window 1 Source count becomes 0
6. reload window 2, observe no archive content list
7. click "Offline" again to bring window 1 online.
8. observe window 2 gets archive content list
9. observe window 1 source count now becomes -1

**Comment by karissa** [comment]
@clkao have you reinstalled your node_modules/hybrid-swarm? I sent a patch which should fix the sources #

**Comment by clkao** [comment]
Right, the source # is correct after updating hyperdrive-archive-swarm and hybrid-swarm

**Comment by clkao** [comment]
After laptop sleeps for a while, if I turn window 1's network connection to offline and back in devtool, I don't see the two eventsource xhr requests.  So at some point those requests might have given up.

**Comment by clkao** [comment]
ok apparently there's no retry logic for `subscribe` in webrtc-swarm, so it relies on signalhub's event-source-stream request to do the retry, which is by default on and infinite.

**But** event-source-stream ships with a browser version which relies on EventSource's native retry logic, and apparently it can fail and emit Error in some cases.

**Comment by mafintosh** [comment]
@clkao do you know in which cases it emits errors vs retries? (the native event source)

**Comment by clkao** [comment]
No, i didn't find the document about the ESS retry behaviour.  (And this is just currently my theory why things don't work)

**Comment by karissa** [comment]
This is from the old version
