### ISSUE TITLE
option to download non-zip version of individual files

### ISSUE THREAD

**Issue by clkao** [datproject/datproject.org#275]
When downloading a small csv, it's annoying to end up getting a zip

**Comment by karissa** [comment]
yeah this would be good! I spent an afternoon once trying to get streamsaver to work -- he published it to NPM but the dependency chain is still messed up. https://github.com/creatorrr/web-streams-polyfill/issues/2

**Comment by karissa** [comment]
looks like someone fixed the web-streams-polyfill bug so it might be doable now
