### ISSUE TITLE
forgot password button

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#346]
![2-dat land - log in slides down](https://cloud.githubusercontent.com/assets/39759/19343232/e5347e40-9167-11e6-86a3-06662e091d98.png)

**Comment by Kriesse** [comment]
@karissa I added a placeholder link. For simplicity & consistency's sake, let's re-use the modal style here and ditch the top-bar.

Current state:

![image](https://cloud.githubusercontent.com/assets/53684/21950289/2e7abacc-d9ae-11e6-8bdd-3b95e6a0aad3.png)

**Comment by karissa** [comment]
https://github.com/staticland/staticland-api/blob/master/lib/handlers/accounts.js#L62-L86

**Comment by clkao** [comment]
also need something like the client shim that calls to the api: https://github.com/staticland/staticland-ui/blob/279549441561d86aea0f28ea48d6c8d51a3737ea/pages/accounts/reset-password.js

**Comment by clkao** [comment]
This is working in #457 with the api implemented in #456.  It's unstyled at the moment, but i think it should be okay?
