### ISSUE TITLE
email not sending on production

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#392]
township should have email verification

**Comment by karissa** [comment]
waiting for @joehand to set up the DNS records on datproject.org so we can send from noreply@datproject.org

**Comment by karissa** [comment]
@joehand  i added you to the postmark. seems like datproject.org still doesn't have the right DKIM and SPF. Do you have time to login to postmark and click 'sender signatures' to make sure those show up correctly? Thanks!

**Comment by joehand** [comment]
working!

**Comment by karissa** [comment]
woot thanks!

**Comment by clkao** [comment]
Is this working? I tried registering a new account on prod and didn't get any email.  i can already login with the CLI though.

**Comment by joehand** [comment]
We are getting errors in postmark:

```
ErrorCode: '400', Message: 'The 'From' address you supplied ("Dat Project" <ghost@blog.datproject.org>) is not a Sender Signature on your account. Please add and confirm this address in order to be able to use it in the 'From' field of your messages.'.
```

Something about the dns switch for our blog. Let me verify dns. I am not sure where the from address gets set.

**Comment by joehand** [comment]
DNS looks okay but there is a lot there so I could be missing something.

**Comment by joehand** [comment]
The other issue is that there've only been two attempted emails (none in the last month). Is something else about email verification broken?

**Comment by karissa** [comment]
Attempting to fix this by following this example: https://github.com/namshi/docker-smtp 

https://github.com/datproject/datproject.org/commit/0302503f2e4cf9d495386b0df4a074a4d882175b

**Comment by karissa** [comment]
Still can't seem to replicate this issue locally nor fix it on master.datproject.org despite switching to smtp, has anyone had any luck with that?

**Comment by karissa** [comment]
Separating this into a different issue, renaming this one 'email not sending bug'
