### ISSUE TITLE
/explore view UI

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#394]
UI for list view should be tidied up. Currently it's at `/list` but it really should be at `/browse`. So this issue is:

- [x] UI: design for viewing all of the publicly available dats
- [x] UX: how does the user get to this view?

**Comment by Kriesse** [comment]
Do we want to start thinking about filter / search, and maybe something like "featured" dats?
Or just design a list for now, and discuss everything else in separate issues later?

About the routing: What do you think about `/explore` instead of `/browse`?

**Comment by karissa** [comment]
`/explore` is good.

I'd say let's start with a simple view that might include a filter search box at the top, yeah! But very simple.

**Comment by Kriesse** [comment]
@karissa Sorry for dropping the ball on this. 
- Is this still a priority? Ready to work on it, let me know.
- Is any of this already implemented?

**Comment by karissa** [comment]
Hi @Kriesse 

I just added a script today that adds two example dats to an existing user. You can run it by typing

```
node scripts/add-dats-to-user.js <email> <password>
```

You can go to `/explore` and see the page:
<img width="1250" alt="screen shot 2017-04-06 at 5 07 43 pm" src="https://cloud.githubusercontent.com/assets/633012/24780414/ffee4ca8-1aeb-11e7-996d-e29e1aa6561f.png">


 @clkao can also help you get things set up if I'm not available.

Thanks!1

**Comment by Kriesse** [comment]
First Wireframe – Idea is to have 3 (or more) featured (=manually curated) dats on top, then a list of all publicly available dats. 

![image](https://cloud.githubusercontent.com/assets/53684/24970856/2565398c-1fb6-11e7-81de-c8f218b38318.png)

**Comment by yoshuawuyts** [comment]
Looking neat! I wrote a reddit-like ranking algorithm we can use to keep
the content list updated if we like (
https://github.com/yoshuawuyts/pretty-hot-ranking-algorithm)

**Comment by Kriesse** [comment]
@karissa As discussed, the profile page (/username) could follow the same pattern for now.
So instead of listing a user's Dats in the small sidebar, they would be all listed on this page.

![image](https://cloud.githubusercontent.com/assets/53684/24972176/c07ce056-1fba-11e7-867e-5e91f0ec65e8.png)

**Comment by karissa** [comment]
nice!

**Comment by karissa** [comment]
We also talked about:
 * removing 'read only' because mostly all dats in this view are read only.
 * making last updated be relative and easy to scan in this view
 * potentially not having the 'download' button, just 'copy link'

**Comment by Kriesse** [comment]
Updated Mockup. @karissa Let's start implementing this and iterate on the details in the browser?

![image](https://cloud.githubusercontent.com/assets/53684/25002834/b3b65900-204c-11e7-9f3b-b20a492a72f4.png)

**Comment by Kriesse** [comment]
@karissa I got started here:
https://github.com/datproject/datproject.org/pull/534

Can you help to make some links and buttons work:

- [ ] copy link
- [ ] preview
- [ ] nicer, relative format for date of last edit (e.g. "10 minutes ago")

**Comment by Kriesse** [comment]
merged, closing
