### ISSUE TITLE
Consortium of Projects - broken images

### ISSUE THREAD

**Issue by rzelnik** [datproject/datproject.org#40]
The datproject.org / dat.foundation home page shows broken images in the "Consortium of Projects" section when the page is loaded through dat protocol.

![dat foundation homepage](https://user-images.githubusercontent.com/610651/57966430-10f0b380-7952-11e9-8c21-71fd46f0489e.png)

It works well when it's shown through https.

**Comment by joehand** [comment]
Ya I was looking at this and really have no idea what is going on there. The new ones are in the same place as the old ones. ANd the files are there if you view source. Will need to dig a bit more but thanks for reminder.

**Comment by joehand** [comment]
I wonder if this is a beaker error?

@pfrazee if you visit the library, the new images show up:

beaker://library/dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330/public/img

But if you visit the directory via url only the old ones are there:

dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330/public/img/

**Comment by joehand** [comment]
Ah nevermind, user error!

The images were in `public/img` but not `dist/public/img` which is what beaker was looking for. The build tool was only copying some of the images for some reason?

Should be fixed! Thanks.
