### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by Kriesse** [datproject/datproject.org#433]
We're currently serving 2 CSS files in production. 
There's probably a few other easy performance wins, like gzipping stuff, optimizing images etc.

**Comment by yoshuawuyts** [comment]
quite been enjoying https://github.com/purifycss/purifycss recently

**Comment by karissa** [comment]
Now we're using 1 CSS file in production but it's still not minified.

anyone feeling ambitious? we can try to get this in the next release
