### ISSUE TITLE
Avoid FOIC

### ISSUE THREAD

**Issue by Kriesse** [datproject/datproject.org#434]
FOIC = Flash Of Invisible Content = while custom webfonts are loading there is no text rendered on the page (in Chrome and Safari, Firefox displays a system font while loading the font files). Encountered this on a slow mobile connection, the page does not show any text for 1 minute+.

https://developers.google.com/fonts/docs/webfont_loader

**Comment by karissa** [comment]
Is this fixed now after using more sheetify stuff?
