### ISSUE TITLE
press regarding open.whitehouse.gov

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#440]
The new whitehouse deleted all of the whitehouse open government data (https://open.whitehouse.gov/browse) which was a socrata instance. We have the data backed up though! Which is exciting because we can really show off what dat can do and why it's useful to have a distributed model for data.

- [x] put that hash on the site
- [ ] blog post
- [ ] #ACoolHashTag and some @Tweets
- [ ] website - maybe reorder things to have some examples higher up, potentially prioritizing the blog post about what is new?
- [ ] newsletter

**Comment by dmil** [comment]
Hello @karissa - I'm just wondering if any data was deleted that hasn't been archived at https://open.obamawhitehouse.archives.gov/search

Also, would you mind sharing the "Open Dat Link" for the data that you have downloaded? Thanks!

**Comment by maxogden** [comment]
@dmil https://gist.github.com/maxogden/d1e3f14bb9253ef9638a40826b000f08 working on a dat link soon

**Comment by dmil** [comment]
Thanks!
