### ISSUE TITLE
Archiver Changes Feed

### ISSUE THREAD

**Issue by joehand** [datproject/datproject.org#445]
Two things I saw yesterday, re: https://github.com/datproject/datproject.org/blob/master/server/dats.js#L63

1. I think `dontShare` changed to `announce` in the options: https://github.com/mafintosh/discovery-swarm#swjoinkey-opts
2. Should we be joining the changes feed at all?

(1) also needs to be updated in https://github.com/datproject/datproject.org/blob/master/server/dats.js#L77

@karissa Do you remember where the dontShare code came from? ~I feel like I saw it somewhere else and we had forgotten to update it.~ Found it in archiver-server. Was there something else we need to add/change in archiver-server to use that?

**Comment by karissa** [comment]
OH nice thanks.

Yes, we'll probably want the changes feed to do cool history views in the future... but that's not right now.

**Comment by karissa** [comment]
Going to not join the changes feed, and am taking defaults for `announce`
