### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#446]
When you are logged in, you see your profile picture on the top right. When you click it, you see your profile page.

Right now we have a sidebar for the user but it should be its own page.

**Comment by Kriesse** [comment]
@karissa What should be on the profile page? Long-term I'm thinking something like e.g. the github profile page, but what can we have right now?

- username
- avatar
- list of dats that user owns / created?
- email? 
- location?

**Comment by karissa** [comment]
Yeah... No location, probably Description instead.

**Comment by karissa** [comment]
Since we have a profile sidebar when you click your username, let's keep that for now. After we launch the User Accounts milestone at 1.1.0, let's revisit the profile page.
