### ISSUE TITLE
docs on using `dat publish` to publish a dat

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#449]
what does publishing a dat mean, how it it done from the cli, etc?

- [x] docs.datproject.org
- [x] FAQ
- [x] Cookbook
- [ ] landing page text

**Comment by clkao** [comment]
should also hint on user's own (empty) profile page

**Comment by karissa** [comment]
nice idea @clkao

**Comment by karissa** [comment]
need to finish landing page text but going to work that into a different issue for a major overhaul
