### ISSUE TITLE
how do I see the production logs of a running container?

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#451]
I need to debug a 502 gateway error that I'm seeing on beta and master but not locally.

**Comment by karissa** [comment]
@clkao ?

**Comment by clkao** [comment]
Right now it's docker logs datfolder_app_1
Karissa McKelvey <notifications@github.com>於 2017年2月17日 週五，02:08寫道：

**Comment by karissa** [comment]
awesome! got it
