### ISSUE TITLE
yoshua puts something more than emojis in his bio

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#465]
@yoshuawuyts :)

**Comment by yoshuawuyts** [comment]
Haha, I didn't write my bio - you actually don't like it tho? Thought it
was both a bit cutesy and cheeky ✨

**Comment by karissa** [comment]
Hah. :) Definitely cutesy and cheeky. It's a nice space to plug projects you've invested time into and gives folks an idea about you!
