### ISSUE TITLE
Back Button Broken // Shareable Subfolder URLs

### ISSUE THREAD

**Issue by Miserlou** [datproject/datproject.org#472]
To repro:

Go to https://datproject.org/dat/6fa91405f280c30cedd461dfcd3b4fffffb27759e26f8135b7cbdfe08870ccb2

Click on any folder

Press your Browser's back button

You are now on the homepage again.

Super annoying! Also means you can't share sub-folders!

Surely you could fix this with URL anchors?

**Comment by karissa** [comment]
Nice catch! This will go into our next milestone

**Comment by karissa** [comment]
out in 1.0.3!
