### ISSUE TITLE
update examples dats

### ISSUE THREAD

**Issue by clkao** [datproject/datproject.org#498]
They need to be published with the new hypercore as well.  old ones should live during the transition.

**Comment by clkao** [comment]
This is done, except cacivicdata is not showing up in preview.

**Comment by karissa** [comment]
Now none of the dats are working, but we have a new module called hypercored which can handle these for us. I wonder if we should use that instead?

**Comment by karissa** [comment]
Fixed now by adding them to 'services' in google2.publicbits.org
