### ISSUE TITLE
dependency lint

### ISSUE THREAD

**Issue by clkao** [datproject/datproject.org#503]
from depcheck:

Unused dependencies
* sheetify-nested
* archiver-server
* babel-preset-es2015
* babelify
* body
* dat-colors
* dat-design
* from2
* handlebars
* level
* node-sass-magic-importer
* sqlite3
* through-timeout

**Comment by karissa** [comment]
closed with https://github.com/datproject/datproject.org/commit/8fc4d8ddef8a4ed006fbd1e109bdde5b462ada9b
