### ISSUE TITLE
meta data not rendered

### ISSUE THREAD

**Issue by juliangruber** [datproject/datproject.org#515]
https://master.datproject.org/f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062 has a dat.json with contents

```json
{
  "title": "Densho Names Registry",
  "url": "dat://f34f99538702f3b55ea3b88c9e374fb72db0ca35903c2249aaa09280accc2062",
  "description": "Names and other information about the individuals held in the ten WRA camps during the WWII incarceration",
  "author": "Densho Digital Repository",
  "name": "densho"
}
```

however the UI doesn't reflect that:

<img width="1680" alt="screen shot 2017-04-04 at 09 35 16" src="https://cloud.githubusercontent.com/assets/10247/24645822/0608864a-191a-11e7-86ee-96162e510eed.png">

This is the case on master and the currently deployed version.

**Comment by karissa** [comment]
Yeah, disabled it because it was slow -- we're going to do this in the next release, see #323
