### ISSUE TITLE
Add last modified time

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#521]
Add a detail to the archive page that is 'last modified' which is simply a reduction of all the last modified to show the most recent time. For example, if we have three files:

hello.csv 3 months ago
hola.csv  2 months ago
goodbye.json 1 day ago

The archive would be 'updated 1 day ago'.

This was requested by the Data folks in the City government of Philadelphia

**Comment by Kriesse** [comment]
@karissa There's already style + markup for the last modified time, just no data (screenshot just shows data added via inspector).
Can you help?

![image](https://user-images.githubusercontent.com/53684/27035282-0f31c2de-4f81-11e7-80c3-6ed42031763a.png)

**Comment by karissa** [comment]
Hey @Kriesse sorry I wasn't clear enough. The style and markup work for individual files (folders don't have a last modified time). This issue is to have an *overall* last modified time for the archive.

**Comment by Kriesse** [comment]
@karissa Ah got it, thanks for clarifying!

**Comment by Kriesse** [comment]
- [ ] Explore List of Dats: https://datproject.org/explore
- [ ] Archive Page, e.g.https://datproject.org/karissa/BattleDecks

Added a placeholder, looks like this but still needs real data:
![image](https://user-images.githubusercontent.com/53684/27177570-24085dba-51c7-11e7-98e7-59ad169375e6.png)
