### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#528]
A public profile page to be linked to from `user-panel.js`

Probably /~:username

**Comment by Kriesse** [comment]
A first iteration should show:

- Username
- List of user's dats
- Number of user's dats
- Date when user joined

To make this page a bit more useful, we should have:

- Firstname, Lastname
- Profile Photo
- Location
- Links to other profiles (github, twitter)
- Email

We’ll need an edit page where the user can enter and edit their data.


## First mockup:

![image](https://cloud.githubusercontent.com/assets/53684/25002413/95cd70c4-204a-11e7-8a87-7037b6fe7a4e.png)

**Comment by karissa** [comment]
<img width="1245" alt="screen shot 2017-05-03 at 11 20 16 am" src="https://cloud.githubusercontent.com/assets/633012/25675229/8090e242-2ff2-11e7-8088-35f7dd75316a.png">
How does something more like this layout (don't mind header style)?

We don't have featured datasets yet and we want to keep it simple for now.

**Comment by Kriesse** [comment]
@karissa Yup, good idea to save some space! I suggest to implement the one above first, then switch to the second layout at a tablet-width breakpoint.

## Mockups

![username profile page mobile](https://cloud.githubusercontent.com/assets/53684/25683111/02728258-305b-11e7-9f09-06e0b4ebfd30.png)
![username profile page](https://cloud.githubusercontent.com/assets/53684/25683110/02724432-305b-11e7-865d-352da308d93c.png)

**Comment by karissa** [comment]
Here's the other idea 
<img width="781" alt="screen shot 2017-05-03 at 3 18 59 pm" src="https://cloud.githubusercontent.com/assets/633012/25684022/de6f97e8-3013-11e7-8736-e0f5eda426c4.png">

**Comment by karissa** [comment]
cool!

**Comment by Kriesse** [comment]
merged, closing
