### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#530]
Incorporate a 'health' tab into the archive view page that looks like health.datproject.org/:key

We could take that frontend, would be nice to make it a standalone component.

@Kriesse how does the user get to the health of the dat from the archive view page?

**Comment by joehand** [comment]
Started by porting hyperhealth web over to https://github.com/datproject/dat-elements/tree/health-element. 

It uses tachyons right now and all comes as one element, so may need to make it a bit more standalone before merging there.

**Comment by karissa** [comment]
OK I did a little prototype and pushed it to master, Check it out #591
