### ISSUE TITLE
copy thoughts

### ISSUE THREAD

**Issue by karissa** [datproject/datproject.org#541]
Dat allows people to:
* Store and remotely backup files using advanced encryption without requiring any technical know-how
* Take back full ownership of data by storing everything on-premises and retaining control of all storage devices
* Avoid any dependence on centralized servers or private companies that may not have the users’ interests in mind
* Avoid depending on any single points of failure, such as centralized, private servers or the wider internet in general
* Share and collaborate on documents and other data with the goal of having similar capabilities of Dropbox

written by @jayrbolton

**Comment by maxogden** [comment]
@joehand likes the term "in place, continuous archiving"
