### ISSUE TITLE
Intro for this release

### ISSUE THREAD

**Issue by clkao** [datproject/datproject.org#545]
### communication

- [x] create a blog post to explain why the migration happens (@karissa ?)
- [x] update the docs for SLEEP (@joehand)
- [ ] possibly video (@juliangruber)
- [ ] tweets and stuff (@yoshuawuyts ?)

**Comment by juliangruber** [comment]
moved the main issue from dat-desktop to here, as it makes more sense

**Comment by juliangruber** [comment]
i assigned some people as a suggestion, does that work for everybody?

**Comment by karissa** [comment]
Started a blog post, you can see it here: https://blog.datproject.org/ghost/18/

**Comment by karissa** [comment]
Did a release https://github.com/datproject/datproject.org/releases/tag/1.1.0

**Comment by karissa** [comment]
I think we should still make a video but I'm going to close this
