### ISSUE TITLE
Seeing wrong data when registering my account

### ISSUE THREAD

**Issue by Kriesse** [datproject/datproject.org#557]
I registered my account on datproject.org, seeing @karissa's data when I try to edit my profile:

![image](https://cloud.githubusercontent.com/assets/53684/26544540/76c525dc-4462-11e7-960f-2c14f6707bae.png)

**Comment by spetex** [comment]
Exact same thing for me now. That really spooked me. I though I am hacking someone's account.

**Comment by karissa** [comment]
fixed on master, great catch! https://github.com/datproject/datproject.org/commit/cbcb2250954a1aa499af3c04a0b08a30ead73588
