### ISSUE TITLE
Add Dat Paper to Website

### ISSUE THREAD

**Issue by slavakurilyak** [datproject/datproject.org#559]
Consider adding the [dat paper](https://github.com/datproject/docs/blob/master/papers/dat-paper.pdf) on [datproject.org](http://datproject.org) in order for [Google Scholar](https://scholar.google.ca/intl/en/scholar/inclusion.html) to index the website

**Comment by karissa** [comment]
Yeah, down with this! Along with that, I think that it'd be smart to add some more info about what is awesome about dat on the front page. Beaker has a nice example to pull from.
