### ISSUE TITLE
Permissions are missing, layout misalignment

### ISSUE THREAD

**Issue by Kriesse** [datproject/datproject.org#588]
On archive pages, the permissions are missing.
The empty div is still rendered, and that causes the layout misalignment:
See e.g. 
https://datproject.org/64375abb733a62fa301b1f124427e825d292a6d3ba25a26c9d4303a7987bec65

![image](https://user-images.githubusercontent.com/53684/27177806-061c9cf2-51c8-11e7-9b4a-102800d1a3f5.png)

**Comment by karissa** [comment]
Will remove the permissions div

**Comment by karissa** [comment]
fixed by 1494e27 but we should probably open another issue to revisit how someone can delete their own dat using this page (which would only be available to the owner)
