### ISSUE TITLE
blog redirect links

### ISSUE THREAD

**Issue by joehand** [datproject/datproject.org#599]
A few issues I saw:

* blog link in footer should point to blog.datproject.org
* [regular redirect](https://github.com/datproject/datproject.org/blob/master/server/router.js#L30-L32) isn't working right now
* [Bad redirect code in router](https://github.com/datproject/datproject.org/blob/master/server/router.js#L98-L100)

**Comment by karissa** [comment]
oh nice catches

**Comment by karissa** [comment]
fixed in https://github.com/datproject/datproject.org/commit/9f5d7ed9873fc3190c2217f0a27991af2ffe07ac

the regular redirect seems to be working for me.
